import {test,expect,type Page,type Route} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
import AxeBuilder from '@axe-core/playwright';

async function ready(page:Page,path='/') {await page.goto(path);await expect(page.getByRole('heading',{level:1})).toBeVisible();await expect(page.getByText('Wczytywanie danych…')).toHaveCount(0);}
async function login(page:Page,role='operator') {await page.getByRole('button',{name:'Stanowisko operatora',exact:true}).click();await page.getByLabel('Rola w demonstracji').selectOption(role);await page.getByRole('button',{name:'Wejdź do demonstracji'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByLabel('Wyloguj się')).toBeVisible();}
async function nav(page:Page,name:string) {if(await page.getByLabel('Otwórz nawigację').isVisible())await page.getByLabel('Otwórz nawigację').click();await page.getByRole('navigation').getByRole('button',{name,exact:true}).click();}
test.beforeAll(async()=>{await mkdir('../../artifacts/screenshots',{recursive:true});});

test('public route, boundaries, comparison, keyboard and responsive screenshots',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await ready(page);await expect(page.locator('.metric-card').first()).toContainText('9');await expect(page.locator('.metric-card').nth(1)).toContainText('+9');await expect.poll(async()=>Number(await page.locator('.city-map').getAttribute('data-rendered-edges'))).toBeGreaterThan(0);await page.screenshot({path:'../../artifacts/screenshots/overview-desktop.png',fullPage:false});
 await nav(page,'Porównanie wariantów');await expect(page.locator('.comparison-card').nth(1)).toContainText('25');await expect(page.locator('.comparison-card').first()).toContainText('16');const maps=page.locator('.comparison-maps .city-map');await expect(maps).toHaveCount(2);for(let index=0;index<2;index++)await expect.poll(async()=>Number(await maps.nth(index).getAttribute('data-rendered-edges'))).toBeGreaterThan(0);const originalCamera=await maps.first().getAttribute('data-map-camera');await maps.first().getByRole('button',{name:'Przybliż mapę'}).click();await expect.poll(async()=>{const first=await maps.first().getAttribute('data-map-camera');return first!==originalCamera&&first===await maps.last().getAttribute('data-map-camera');}).toBe(true);const impacts=page.getByRole('region',{name:'Skutki zamknięć osobno i razem'}).locator('tbody tr');await expect(impacts).toHaveCount(3);await expect(impacts.nth(0).locator('td').nth(1)).toHaveText('0');await expect(impacts.nth(1).locator('td').nth(1)).toHaveText('0');await expect(impacts.nth(2).locator('td').nth(1)).toHaveText('9');await maps.first().getByRole('button',{name:'Pokaż cały obszar'}).click();await expect.poll(async()=>await maps.first().getAttribute('data-map-camera')===await maps.last().getAttribute('data-map-camera')).toBe(true);const timeControl=page.getByRole('slider',{name:'Czas porównania map'});await timeControl.focus();await page.keyboard.press('Home');for(let step=0;step<24;step++)await page.keyboard.press('ArrowRight');await expect(page.locator('.comparison-maps .comparison-grid>div').first()).toContainText('Znana bariera');await expect(page.locator('.comparison-maps .comparison-grid>div').last()).toContainText('Potwierdzone w danych');await page.evaluate(()=>(document.activeElement as HTMLElement)?.blur());await page.locator('.comparison-maps').screenshot({path:'../../artifacts/screenshots/comparison-desktop.png',animations:'disabled'});await page.getByText('Ustaw zakres analizy i własny wariant',{exact:true}).click();await page.getByLabel('Początek horyzontu · Warszawa').fill('2026-10-03T10:00');await page.getByLabel('Ostatnie wyjście · Warszawa').fill('2026-10-03T18:00');await page.getByRole('button',{name:'Oblicz wybrany zakres i wariant'}).click();await expect(page.locator('.comparison-card .timeline-note').first()).toContainText('10:00 do 18:00');
 await nav(page,'Moje dojście');await page.getByRole('link',{name:'Przejdź do treści'}).focus();await page.keyboard.press('Enter');await expect(page.locator('#main-content')).toBeFocused();await expect(page).toHaveURL(/#resident$/);await page.getByLabel('Wyjście · czas w Warszawie').fill('2026-10-03T09:00');await page.getByRole('button',{name:'Sprawdź dojście',exact:true}).click();await expect(page.getByRole('heading',{name:'Masz dojście potwierdzone w danych'})).toBeVisible();
 await page.getByLabel('Wyjście · czas w Warszawie').fill('2026-10-03T10:00');await page.getByRole('button',{name:'Sprawdź dojście',exact:true}).click();await expect(page.getByRole('heading',{name:/^Znana bariera(?: na dojściu)?$/})).toBeVisible();
 await page.getByLabel('Wyjście · czas w Warszawie').fill('2026-10-03T09:00');await page.getByRole('button',{name:'Sprawdź dojście',exact:true}).click();await expect(page.locator('.route-result')).toContainText('Masz dojście');
 await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.locator('.sidebar').evaluate(el=>el.getBoundingClientRect().right)).toBeLessThanOrEqual(0);await page.screenshot({path:'../../artifacts/screenshots/resident-mobile-full.png',fullPage:true});await page.locator('.route-result').evaluate(el=>window.scrollTo(0,el.getBoundingClientRect().top+window.scrollY-16));await page.screenshot({path:'../../artifacts/screenshots/resident-mobile.png',fullPage:false,animations:'disabled'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();
 await page.keyboard.press('Tab');expect(await page.evaluate(()=>document.activeElement?.tagName)).not.toBe('BODY');expect(errors).toEqual([]);
});

test('accessibility of resident, comparison and operator forms',async({page})=>{
 await ready(page);for(const name of ['Ciągłość dostępu','Moje dojście','Porównanie wariantów']){await nav(page,name);if(name==='Porównanie wariantów')await expect(page.locator('.results-details')).toBeVisible();const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(result.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)})),name).toEqual([]);}
 await login(page);await nav(page,'Kontrola terenowa');const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(result.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}))).toEqual([]);
});

test('resident report, private status, moderated warning invalidates second session, rejected warning clears',async({page,browser})=>{
 await ready(page,'/#resident');await expect(page.locator('.app-shell')).toHaveAttribute('data-live-transport','sse');await page.getByRole('button',{name:'Sprawdź dojście',exact:true}).click();await expect(page.locator('.route-result')).toContainText('Masz dojście');
 await page.locator('.result-actions').getByRole('button',{name:'Zgłoś rozbieżność'}).click();await page.getByLabel('Miejsce lub obiekt').selectOption('crossing-y');const description=`Test przeglądarkowy ${Date.now()}: przeszkoda na dojściu południowym.`;await page.getByLabel('Opis obserwacji').fill(description);await page.getByLabel('Zdjęcie obserwacji (opcjonalne)').setInputFiles({name:'syntetyczny-test.png',mimeType:'image/png',buffer:await page.screenshot({clip:{x:0,y:0,width:100,height:100}})});const photoResponse=page.waitForResponse(r=>r.url().includes('/photos')&&r.request().method()==='POST',{timeout:60000});await page.getByRole('button',{name:'Wyślij zgłoszenie',exact:true}).click();await expect(page.getByRole('heading',{name:'Zgłoszenie zapisane na serwerze'})).toBeVisible();expect((await photoResponse).status()).toBe(201);await expect(page.getByText('Zdjęcie zapisano prywatnie.',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Gotowe',exact:true}).click();
 const operatorContext=await browser.newContext();const operator=await operatorContext.newPage();await ready(operator);await login(operator);await nav(operator,'Dowody i sprawy');await operator.locator('.report-row').filter({hasText:description}).click();await expect(operator.getByRole('img',{name:'Zdjęcie obserwacji 1'})).toBeVisible();await expect.poll(()=>operator.getByRole('img',{name:'Zdjęcie obserwacji 1'}).evaluate(el=>(el as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);await operator.getByLabel('Uzasadnienie i zakres decyzji').fill('Test syntetyczny: sprawdzono obiekt i lokalizację, publikacja ostrzeżenia do kontroli.');
 const publication=Date.now();await operator.getByRole('button',{name:'Zapisz decyzję moderacji'}).click();await expect(operator.getByText('Decyzja zapisana z uzasadnieniem.')).toBeVisible();await expect(page.getByText('Ten wynik jest z poprzedniej wersji.',{exact:false})).toBeVisible({timeout:5000});expect(Date.now()-publication).toBeLessThan(7000);
 await operator.getByLabel('Decyzja operatora').selectOption('reject');await operator.getByLabel('Uzasadnienie i zakres decyzji').fill('Test kontrolny zakończony. Nie stwierdzono przeszkody w danych syntetycznych.');await operator.getByRole('button',{name:'Zapisz decyzję moderacji'}).click();await expect(operator.locator('.report-row').filter({hasText:description})).toContainText('Odrzucone');await page.getByRole('button',{name:'Sprawdź status'}).click();await expect(page.locator('.evidence-row').filter({hasText:'Sprawa'})).toContainText('Odrzucone');await operatorContext.close();
 const privateCase=await page.evaluate(()=>JSON.parse(localStorage.getItem('mbod-private-reports-v1')||'[]')[0]);const importedContext=await browser.newContext();const imported=await importedContext.newPage();let tokenInRequest=false;imported.on('request',r=>{if(r.url().includes(privateCase.token))tokenInRequest=true;});await imported.goto(`${new URL(page.url()).origin}/#resident?report=${encodeURIComponent(privateCase.id)}&token=${encodeURIComponent(privateCase.token)}`);await expect(imported.getByRole('heading',{name:'Twoje zgłoszenia'})).toBeVisible();await expect(imported).toHaveURL(/\/#resident$/);await imported.reload();await imported.getByRole('button',{name:'Sprawdź status'}).click();await expect(imported.locator('.evidence-row').filter({hasText:'Sprawa'})).toContainText('Odrzucone');expect(tokenInRequest).toBe(false);await importedContext.close();
});

test('field task, unpublished measurement, review, ownership and scenario lifecycle',async({page})=>{
 await ready(page);await login(page);await nav(page,'Porównanie wariantów');const scenario=`Plan UI ${Date.now()}`;await page.getByLabel('Nazwa scenariusza',{exact:true}).fill(scenario);await page.getByLabel('Osoba odpowiedzialna').fill('Michał Kiełtyka');await page.getByLabel('Wykonawca',{exact:true}).fill('Zespół testowy');await page.getByRole('button',{name:'Zapisz i oceń scenariusz'}).click();await expect(page.locator('.scenario-row').filter({hasText:scenario})).toContainText('Oceniony wariant',{timeout:60000});await page.locator('.scenario-row').filter({hasText:scenario}).click();await page.getByRole('button',{name:'Zatwierdź plan'}).click();await expect(page.locator('.decision-stages .current')).toHaveText('Plan zatwierdzony');await page.getByRole('button',{name:'Rozpocznij realizację'}).click();await expect(page.locator('.decision-stages .current')).toHaveText('W realizacji');
 await nav(page,'Kontrola terenowa');await page.getByRole('button',{name:'Nowa kontrola'}).click();const taskName=`Kontrola otwarcia UI ${Date.now()}`;await page.getByLabel('Tytuł zadania').fill(taskName);await page.getByRole('combobox',{name:'Obiekt',exact:true}).selectOption('crossing-y');await page.getByLabel('Sprawdzana cecha').selectOption('open');await page.getByLabel('Metoda',{exact:true}).fill('Obserwacja testowa kontrolowanego grafu');await page.getByRole('button',{name:'Zapisz zadanie'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.locator('.task-row').filter({hasText:taskName}).click();await page.getByRole('combobox',{name:/Wynik obserwacji/}).selectOption('true');await page.getByLabel('Metoda pomiaru').fill('Obserwacja testowa kontrolowanego grafu');await page.getByLabel('Czas obserwacji · Warszawa').fill('2026-10-03T09:00');await page.getByLabel('Ważność do · Warszawa').fill('2026-10-03T23:59');await page.getByLabel('Nakład kontroli').fill('4');await page.getByLabel('Zdjęcie pomiaru (opcjonalne)').setInputFiles({name:'pomiar-testowy.png',mimeType:'image/png',buffer:await page.screenshot({clip:{x:0,y:0,width:100,height:100}})});const taskPhotoResponse=page.waitForResponse(r=>r.url().includes('/tasks/')&&r.url().includes('/photos')&&r.request().method()==='POST',{timeout:60000});const observationResponse=page.waitForResponse(r=>r.url().includes('/observe')&&r.request().method()==='POST');await page.getByRole('button',{name:'Wyślij pomiar'}).click();const taskPhoto=await taskPhotoResponse;expect(taskPhoto.status()).toBe(201);const photo=await taskPhoto.json();const observed=await (await observationResponse).json();expect(observed.evidence.photo_id).toBe(photo.id);await expect(page.getByRole('img',{name:'Prywatne zdjęcie pomiaru'})).toBeVisible();expect(observed.evidence.status).toBe('pending_review');const evidenceId=observed.evidence.id;
 await nav(page,'Dowody i sprawy');const evidenceRow=page.locator('tr').filter({hasText:evidenceId});await expect(evidenceRow).toContainText('Pomiar czeka na przegląd');await evidenceRow.getByRole('button',{name:'Publikuj cechę'}).click();await expect.poll(()=>page.getByRole('img',{name:'Zdjęcie przeglądanego pomiaru'}).evaluate(el=>(el as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);await page.getByLabel('Uzasadnienie przeglądu dowodu').fill('Sprawdzono otwarcie tego obiektu w kontrolowanym przykładzie, bez wnioskowania o innych cechach.');await page.getByRole('button',{name:'Zatwierdź publikację cechy'}).click();await expect(evidenceRow).toContainText('Potwierdzone w danych');await page.evaluate(()=>{(document.activeElement as HTMLElement)?.blur();window.scrollTo(0,0);});await expect(page.locator('.page-heading')).toBeInViewport();await page.screenshot({path:'../../artifacts/screenshots/operations-desktop.png',fullPage:false,animations:'disabled'});
 await nav(page,'Porównanie wariantów');await page.locator('.scenario-row').filter({hasText:scenario}).click();await page.getByLabel('Osoba odpowiedzialna').fill('Michał Kiełtyka');await page.getByLabel('Wykonawca',{exact:true}).fill('Zespół testowy');await page.getByLabel('Dowody wykonania lub obserwacji').fill(evidenceId);await page.getByRole('button',{name:'Zapisz wykonanie'}).click();await expect(page.locator('.decision-stages .current')).toHaveText('Wykonanie zapisane');await page.getByRole('button',{name:'Porównaj efekt',exact:true}).click();await expect(page.locator('.effect-report')).toContainText('Zaobserwowana zmiana w modelu');await expect(page.locator('.effect-report .three-values').nth(0)).toContainText('0 h');await page.getByRole('button',{name:'Zapisz ocenę efektu'}).click();await expect(page.locator('.decision-stages .current')).toHaveText('Efekt oceniony');await nav(page,'Kontrola terenowa');await page.getByRole('button',{name:'Nowa kontrola'}).click();const slopeName=`Nachylenie UI ${Date.now()}`;await page.getByLabel('Tytuł zadania').fill(slopeName);await page.getByLabel('Sprawdzana cecha').selectOption('slope_pct');await page.getByLabel('Metoda',{exact:true}).fill('Pomiar nachylenia względem kierunku obiektu');await page.getByRole('button',{name:'Zapisz zadanie'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByLabel('Wynik obserwacji (%)').fill('-2');expect(await page.getByLabel('Wynik obserwacji (%)').evaluate(el=>(el as HTMLInputElement).checkValidity())).toBe(true);await page.getByLabel('Nakład kontroli').fill('6');await page.getByRole('button',{name:'Zapisz szkic offline'}).click();await nav(page,'Porównanie wariantów');await nav(page,'Kontrola terenowa');await page.locator('.task-row').filter({hasText:slopeName}).click();await expect(page.getByLabel('Wynik obserwacji (%)')).toHaveValue('-2');await expect(page.getByLabel('Nakład kontroli')).toHaveValue('6');
});

test('offline reload exposes public saved graph only and retains unsent report draft',async({page,context})=>{
 await ready(page);await login(page);await page.getByRole('button',{name:'Wyloguj się'}).click();await nav(page,'Moje dojście');await page.locator('.page-footer').getByRole('button',{name:'Zgłoś rozbieżność'}).click();await page.getByLabel('Opis obserwacji').fill('Szkic offline testu, niewysłany.');await page.getByRole('button',{name:'Zapisz niewysłany szkic'}).click();await expect(page.getByText('Zgłoszenie nie zostało wysłane.',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Zamknij okno'}).click();
 const cached=await page.evaluate(()=>JSON.parse(localStorage.getItem('mbod-public-view-v1-fixture')||'null'));expect(cached.user).toBeNull();expect(cached.reports).toEqual([]);expect(cached.staff_evidence).toEqual([]);expect(cached.scenarios).toEqual([]);expect(cached.tasks).toEqual([]);expect(JSON.stringify(cached)).not.toContain('token_hash');
 await page.evaluate(async()=>{if('serviceWorker' in navigator)await navigator.serviceWorker.ready;});await context.setOffline(true);await page.reload();await expect(page.getByText('Ostatni zapis:',{exact:false})).toBeVisible();await page.locator('.page-footer').getByRole('button',{name:'Zgłoś rozbieżność'}).click();await expect(page.getByLabel('Opis obserwacji')).toHaveValue('Szkic offline testu, niewysłany.');await page.getByRole('button',{name:'Wyślij zgłoszenie',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Nie można połączyć');await expect(page.getByRole('heading',{name:'Zgłoszenie zapisane na serwerze'})).toHaveCount(0);await context.setOffline(false);await expect(page.locator('.app-shell')).toHaveAttribute('data-live-transport','sse');await page.route('**/api/v1/events?*',route=>route.abort());const fallbackVersion=page.waitForResponse(response=>response.url().includes('/versions?layer=fixture')&&response.status()===200);await page.reload();await expect(page.locator('.app-shell')).toHaveAttribute('data-live-transport','polling');await fallbackVersion;await page.getByRole('button',{name:'Sprawdź dojście',exact:true}).click();await expect(page.locator('.route-result')).toContainText('Masz dojście');
});

test('manual source keeps provenance, extraction stays a candidate and CSV enters review',async({page})=>{
 await ready(page);await login(page);await nav(page,'Źródła i import');const title=`Komunikat UI ${Date.now()}`;await page.getByLabel('Tytuł materiału').fill(title);await page.getByLabel('Wydawca',{exact:true}).fill('Operator danych testowych');await page.getByLabel('Warunki użycia',{exact:true}).fill('CC0, własny materiał testowy');await page.getByLabel('Pełna treść źródłowa').fill('Remont chodnika po południowej stronie ulicy. Ruch pieszy pozostaje utrzymany. Daty wymagają sprawdzenia.');await page.getByRole('button',{name:'Zachowaj źródło',exact:true}).click();await expect(page.getByText('Źródło i surowy zapis zostały zachowane.',{exact:false})).toBeVisible();const source=page.locator('.source-item').filter({hasText:title});await source.locator('summary').click();await source.getByRole('button',{name:'Odczytaj materiał i historię'}).click();await expect(source.locator('.source-text').last()).toContainText('Ruch pieszy pozostaje utrzymany');await source.getByRole('button',{name:'Przygotuj kandydaturę'}).click();await expect(source).toContainText('Kandydatura wymaga kontroli');
 await page.getByRole('button',{name:'Import pliku',exact:true}).click();await page.getByLabel('Format danych').selectOption('csv');await page.getByLabel('Treść danych').fill('title,source_url,publisher,asset_id,start,end,quote\nKomunikat CSV,https://example.org/komunikat,Operator testu,crossing-y,2026-10-03T10:00:00+02:00,2026-10-03T16:00:00+02:00,Ruch pieszy utrzymany\n');await page.getByRole('button',{name:'Przygotuj i sprawdź import'}).click();await expect(page.getByRole('button',{name:'Przejrzyj komunikat: Komunikat CSV'})).toBeVisible();await page.getByRole('button',{name:'Przejrzyj komunikat: Komunikat CSV'}).click();await expect(page.getByLabel('Tytuł materiału')).toHaveValue('Komunikat CSV');
});

test('changing profile invalidates a result and delayed fixture response cannot become observed',async({page})=>{
 await ready(page,'/#resident');await expect(page.locator('.app-shell')).toHaveAttribute('data-live-transport','sse');await page.getByRole('button',{name:'Sprawdź dojście',exact:true}).click();await expect(page.locator('.route-result')).toContainText('Masz dojście');await page.getByText('Dostosuj wymagania',{exact:true}).click();await page.getByLabel('Min. szerokość (m)').fill('2');await expect(page.locator('.route-result')).toContainText('Sprawdź dojście z aktualnymi ustawieniami');await expect(page.locator('.route-result')).not.toContainText('Masz dojście potwierdzone');
 // Hold exactly one real refresh until the user has changed layers. Other SSE
 // refreshes continue normally, and the pending route finishes before reload.
 let capture!:(route:Route)=>void;
 const intercepted=new Promise<Route>(resolve=>{capture=resolve;});
 await page.route('**/api/v1/bootstrap?layer=fixture',route=>capture(route),{times:1});
 await page.evaluate(()=>window.dispatchEvent(new Event('online')));
 const heldRoute=await intercepted;
 const response=await heldRoute.fetch();
 expect(response.status()).toBe(200);
 const body=await response.body();
 expect(JSON.parse(body.toString()).layer).toBe('fixture');
 await page.getByLabel('Przestrzeń danych').selectOption('observed');
 await expect(page.locator('.demo-banner')).toContainText('OBSERWACJE');
 const delivered=page.waitForEvent('requestfinished',request=>request===heldRoute.request());
 await heldRoute.fulfill({status:response.status(),headers:response.headers(),body});
 await delivered;
 await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));
 const cache=await page.evaluate(()=>JSON.parse(localStorage.getItem('mbod-public-view-v1-observed')||'null'));
 if(cache){expect(cache.layer).toBe('observed');expect(cache.graph.layer).toBe('observed');}
 expect(await page.locator('.demo-banner').innerText()).not.toContain('Dane syntetyczne');
 await page.reload();
 await expect(page.getByLabel('Przestrzeń danych')).toHaveValue('observed');
 await expect(page.locator('.demo-banner')).toContainText('OBSERWACJE');
});

test('finite catalog goes through durable worker and chosen saved variant can be approved',async({page})=>{
 await ready(page);await login(page);await nav(page,'Porównanie wariantów');await page.getByText('Katalog alternatyw, zasoby i zależności',{exact:true}).click();const name=`Katalog UI ${Date.now()}`;await page.getByLabel('Nazwa analizy katalogu').fill(name);await page.getByRole('button',{name:'Zapisz i oceń katalog'}).click();const result=page.getByRole('region',{name:'Wynik analizy katalogu'});await expect(result).toBeVisible({timeout:60000});await expect(result).toContainText('Optymalny w zadanym katalogu');await expect(result).toContainText('9');await page.locator('.scenario-row').filter({hasText:name}).click();await page.getByLabel('Osoba odpowiedzialna').fill('Michał Kiełtyka');await expect(page.getByLabel('Wariant zatwierdzany w tym scenariuszu')).toHaveValue(/catalog-/);await page.getByRole('button',{name:'Zatwierdź plan'}).click();await expect(page.locator('.decision-stages .current')).toHaveText('Plan zatwierdzony');
});

test('keyboard skip, modal focus and mobile navigation preserve the active view',async({page})=>{
 await ready(page,'/#resident');await page.getByRole('link',{name:'Przejdź do treści'}).focus();await page.keyboard.press('Enter');await expect(page.locator('#main-content')).toBeFocused();await expect(page).toHaveURL(/#resident$/);
 const trigger=page.locator('.page-footer').getByRole('button',{name:'Zgłoś rozbieżność'});await trigger.focus();await page.keyboard.press('Enter');await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('button',{name:'Zamknij okno'})).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(page.getByRole('button',{name:'Zapisz niewysłany szkic'})).toBeFocused();await page.keyboard.press('Tab');await expect(page.getByRole('button',{name:'Zamknij okno'})).toBeFocused();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(trigger).toBeFocused();await expect(page).toHaveURL(/#resident$/);
 await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.locator('.sidebar').evaluate(el=>(el as HTMLElement).inert)).toBe(true);const menu=page.getByRole('button',{name:'Otwórz nawigację'});await menu.focus();await page.keyboard.press('Enter');await expect(page.getByRole('navigation').getByRole('button',{name:'Moje dojście',exact:true})).toBeFocused();await page.keyboard.press('Escape');await expect(menu).toBeFocused();await expect(menu).toHaveAttribute('aria-expanded','false');await page.keyboard.press('Enter');await page.getByRole('navigation').getByRole('button',{name:'Porównanie wariantów',exact:true}).focus();await page.keyboard.press('Enter');await expect(page).toHaveURL(/#comparison$/);await expect(page.locator('#main-content')).toBeFocused();await expect.poll(()=>page.locator('.sidebar').evaluate(el=>(el as HTMLElement).inert)).toBe(true);await page.goBack();await expect(page).toHaveURL(/#resident$/);await expect(page.getByRole('heading',{level:1})).toHaveText('Dokąd chcesz dotrzeć?');
});
