import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowRight, Building2, ClipboardCheck, Database, Footprints, GitCompareArrows, LayoutDashboard, LogIn, LogOut, Menu, RefreshCw, Send, Settings2, ShieldCheck, WifiOff } from 'lucide-react';
import { api, ApiError, type Bootstrap, type RecordData, cacheGet, cacheSet, dateTime, setCsrf, statusLabel } from './api';
import { Badge, Button, Field, Loading, Modal, Notice } from './ui';
import Resident from './Resident';
import { Comparison, Overview, Resilience } from './Planning';
import { Diagnostics, EvidenceView, FieldTasks, PrivateReports, ReportForm, SourcesView } from './Operations';

const navigation = [
  {id:'overview',label:'Ciągłość dostępu',icon:LayoutDashboard}, {id:'resident',label:'Moje dojście',icon:Footprints},
  {id:'comparison',label:'Porównanie wariantów',icon:GitCompareArrows}, {id:'evidence',label:'Dowody i sprawy',icon:ShieldCheck},
  {id:'field',label:'Kontrola terenowa',icon:ClipboardCheck}, {id:'sources',label:'Źródła i import',icon:Database}, {id:'diagnostics',label:'Utrzymanie',icon:Settings2},
];
function publicCache(data: Bootstrap): Bootstrap {
  const removePrivate = (value: any): any => Array.isArray(value) ? value.map(removePrivate) : value && typeof value === 'object' ? Object.fromEntries(Object.entries(value).filter(([key])=>!['author','reviewer','contact','token_hash','raw_text','storage_path','notes','photo_id','raw','history','review_reason','reason'].includes(key)).map(([key,item])=>[key,removePrivate(item)])) : value;
  const graph=Object.fromEntries(['version','evidence_version','data_version','layer','name','clock','timezone','valid_from','valid_until','coverage','nodes','edges','assets','evidence','profiles','places','entrances','origins','works','restrictions','horizon','bindings','notice'].filter(k=>k in data.graph).map(k=>[k,removePrivate(data.graph[k])]));
  return {layer:data.layer,data_version:data.data_version,graph_version:data.graph_version,graph,restrictions:removePrivate(data.restrictions),staff_evidence:[],user:null,reports:[],tasks:[],scenarios:[],decisions:[],sources:data.sources.map(s=>({id:s.id,title:s.title,url:s.url,publisher:s.publisher,license:s.license,published_at:s.published_at,observed_at:s.observed_at})),pilot_status:data.pilot_status,cached_at:new Date().toISOString()};
}
export default function App() {
  const [view,setView]=useState(()=>new URLSearchParams(location.search).has('report')?'resident':location.hash.slice(1).split('?')[0]||'overview');
  const [data,setData]=useState<Bootstrap|null>(null),[evaluation,setEvaluation]=useState<RecordData|null>(null);
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[offline,setOffline]=useState(!navigator.onLine),[evaluating,setEvaluating]=useState(false);
  const [streamConnected,setStreamConnected]=useState(false);
  const [loginOpen,setLoginOpen]=useState(false),[reportOpen,setReportOpen]=useState(false),[asset,setAsset]=useState<string>(),[mobileOpen,setMobileOpen]=useState(false),[updated,setUpdated]=useState(false);
  const [mobile,setMobile]=useState(()=>matchMedia('(max-width:720px)').matches);const sidebar=useRef<HTMLElement|null>(null),menu=useRef<HTMLButtonElement>(null);
  const [selectedLayer,setSelectedLayer]=useState(()=>cacheGet<string>('mbod-selected-layer-v1')==='observed'?'observed':'fixture');
  const version=useRef<number>(),layer=useRef(selectedLayer),refreshGeneration=useRef(0),evaluationGeneration=useRef(0);
  const refresh=useCallback(async()=>{
    const requestedLayer=layer.current,generation=++refreshGeneration.current;
    try { const fresh=await api<Bootstrap>(`/bootstrap?layer=${requestedLayer}`); if(layer.current!==requestedLayer||refreshGeneration.current!==generation)return; if(version.current!==undefined&&version.current!==fresh.data_version)setUpdated(true); version.current=fresh.data_version;setData(fresh);cacheSet(`mbod-public-view-v1-${layer.current}`,publicCache(fresh));setOffline(false);setError(''); }
    catch(e) {if(layer.current!==requestedLayer||refreshGeneration.current!==generation)return;const networkFailure=e instanceof ApiError&&e.status===0;setOffline(networkFailure);if(!version.current){const cached=networkFailure?cacheGet<Bootstrap>(`mbod-public-view-v1-${requestedLayer}`):null;if(cached){setData({...cached,user:null});version.current=cached.data_version;}else setError((e as Error).message);} }
    finally {if(layer.current===requestedLayer&&refreshGeneration.current===generation)setLoading(false);}
  },[]);
  const evaluate=useCallback(async(request?:RecordData)=>{const requestedLayer=layer.current,generation=++evaluationGeneration.current;setEvaluating(true);try {const result=await api('/analysis/evaluate',{layer:requestedLayer,...request});if(layer.current!==requestedLayer||evaluationGeneration.current!==generation)return;setEvaluation(result);setError('');}catch(e){if(layer.current===requestedLayer&&evaluationGeneration.current===generation)setError((e as Error).message);}finally{if(layer.current===requestedLayer&&evaluationGeneration.current===generation)setEvaluating(false);}},[]);
  useEffect(()=>{void api('/auth/session').then(s=>setCsrf(s.csrf_token||'')).catch(()=>{});void refresh();const handle=setInterval(()=>{void api(`/versions?layer=${layer.current}`).then(v=>{setOffline(false);if(v.data_version!==version.current)void refresh();}).catch(()=>setOffline(true));},3500);const online=()=>{void refresh();};const offline=()=>setOffline(true);window.addEventListener('online',online);window.addEventListener('offline',offline);return()=>{clearInterval(handle);window.removeEventListener('online',online);window.removeEventListener('offline',offline);};},[refresh]);
  useEffect(()=>{if(data&&!evaluation&&!offline)void evaluate();},[!!data,evaluate,offline]);
  useEffect(()=>{const hash=()=>setView(location.hash.slice(1).split('?')[0]||'overview');window.addEventListener('hashchange',hash);return()=>window.removeEventListener('hashchange',hash);},[]);
  useEffect(()=>{const query=matchMedia('(max-width:720px)'),change=()=>setMobile(query.matches);query.addEventListener('change',change);return()=>query.removeEventListener('change',change);},[]);
  useEffect(()=>{if(!('EventSource' in window))return;const requestedLayer=selectedLayer,stream=new EventSource(`/api/v1/events?layer=${encodeURIComponent(requestedLayer)}`);const receive=(event:MessageEvent)=>{try{const payload=JSON.parse(event.data);if(layer.current!==requestedLayer||payload.layer!==requestedLayer)return;if(event.type==='job'){window.dispatchEvent(new CustomEvent('mbod-job-progress',{detail:payload}));}else if(payload.data_version!==version.current)void refresh();}catch{/* A malformed event cannot replace the last verified view; polling remains active. */}};stream.addEventListener('open',()=>{if(layer.current!==requestedLayer)return;setStreamConnected(true);void refresh();window.dispatchEvent(new Event('mbod-stream-connected'));});stream.addEventListener('error',()=>setStreamConnected(false));stream.addEventListener('session',()=>{if(layer.current===requestedLayer)void refresh();});stream.addEventListener('snapshot',receive as EventListener);stream.addEventListener('version',receive as EventListener);stream.addEventListener('job',receive as EventListener);return()=>{stream.close();setStreamConnected(false);};},[selectedLayer,data?.user?.username,data?.user?.role,refresh]);
  useEffect(()=>{if(mobile&&mobileOpen)sidebar.current?.querySelector<HTMLElement>('[aria-current="page"]')?.focus();},[mobile,mobileOpen]);
  const changeLayer=(value:string)=>{layer.current=value;version.current=undefined;refreshGeneration.current++;evaluationGeneration.current++;setEvaluating(false);setSelectedLayer(value);cacheSet('mbod-selected-layer-v1',value);setReportOpen(false);setData(null);setEvaluation(null);setLoading(true);setError('');setUpdated(false);void refresh();};
  const navigate=(id:string)=>{setView(id);location.hash=id;setMobileOpen(false);window.scrollTo({top:0,behavior:'instant'});requestAnimationFrame(()=>document.getElementById('main-content')?.focus());};
  const closeNavigation=()=>{setMobileOpen(false);requestAnimationFrame(()=>menu.current?.focus());};
  const report=(id?:string)=>{setAsset(id);setReportOpen(true);};
  const logout=async()=>{try{await api('/auth/logout',{});setCsrf('');await refresh();}catch(e){setError((e as Error).message);}};
  return <div className="app-shell" data-live-transport={streamConnected?'sse':'polling'}>
    <a className="skip-link" href="#main-content" onClick={event=>{event.preventDefault();document.getElementById('main-content')?.focus();}}>Przejdź do treści</a>
    {mobileOpen&&mobile&&<button className="sidebar-scrim" aria-label="Zamknij nawigację" onClick={closeNavigation}/>}
    <aside ref={element=>{sidebar.current=element;if(element)element.inert=mobile&&!mobileOpen;}} aria-hidden={mobile&&!mobileOpen?true:undefined} className={`sidebar ${mobileOpen?'mobile-open':''}`} onKeyDown={event=>{if(!mobile||!mobileOpen)return;if(event.key==='Escape'){event.preventDefault();closeNavigation();}if(event.key==='Tab'){const items=Array.from(event.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),a[href]')).filter(item=>item.getClientRects().length),first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}}}>
      <a className="brand" href="#overview" onClick={()=>navigate('overview')}><span className="brand-symbol"><Building2 size={25}/><i/></span><span>miasto<span className="brand-second">bez odcięć<span className="brand-dot">.</span></span></span></a>
      <div className="workspace-label"><span className="dot green"/>PRACOWNIA DOSTĘPNOŚCI</div>
      <nav aria-label="Główna nawigacja">{navigation.map(({id,label,icon:Icon},i)=><div key={id}>{i===3&&<span className="nav-section">DANE I WERYFIKACJA</span>}<button className={`nav-item ${view===id?'active':''}`} aria-label={label} aria-current={view===id?'page':undefined} onClick={()=>navigate(id)}><Icon size={19}/><span>{label}</span>{id==='evidence'&&!!data?.reports.length&&<span className="nav-count">{data.reports.length}</span>}</button></div>)}</nav>
      <div className="sidebar-bottom"><div className="pilot-card"><span className="pilot-icon"><ShieldCheck size={20}/></span><strong>Zachowaj dojście<br/>podczas remontu.</strong><p>Porównaj terminy prac i wybierz dostępne obejście.</p><button onClick={()=>navigate('comparison')}>Porównaj harmonogramy <ArrowRight size={14}/></button></div><div className="team-credit">DEFOZO SOFTWARE HOUSE<span>Michał Kiełtyka · HackYeah 2026</span></div></div>
    </aside>
    <div className="workspace" ref={element=>{if(element)element.inert=mobile&&mobileOpen;}}><header className="topbar"><div className="topbar-left"><button ref={menu} className="icon-button mobile-menu" aria-label="Otwórz nawigację" aria-expanded={mobileOpen} onClick={()=>setMobileOpen(true)}><Menu size={23}/></button><span className="breadcrumb">Pracownia <span>/</span> <strong>{navigation.find(n=>n.id===view)?.label||'Ciągłość dostępu'}</strong></span></div><div className="topbar-actions"><select className="layer-select" aria-label="Przestrzeń danych" value={selectedLayer} onChange={e=>changeLayer(e.target.value)}><option value="fixture">Demonstracja</option><option value="observed">Dane obserwowane</option></select><span className={`connection ${offline?'offline':''}`}><span className={`dot ${offline?'amber':'green'}`}/>{offline?'Zapisany widok':'Połączono'}</span>{data?.user?<><span className="user-role">{statusLabel(data.user.role)}</span><button className="icon-button" aria-label="Wyloguj się" onClick={()=>void logout()}><LogOut size={18}/></button></>:<button className="login-button" onClick={()=>setLoginOpen(true)}><LogIn size={16}/>Stanowisko operatora</button>}</div></header>
      <main id="main-content" tabIndex={-1}>
        <div className="demo-banner"><span><Badge tone={selectedLayer==='fixture'?'purple':'amber'}>{selectedLayer==='fixture'?'DEMO':'OBSERWACJE'}</Badge>{selectedLayer==='fixture'?' Przykładowe roboty i dojścia.':' Opublikowane obserwacje. Sprawdź zakres i ważność.'}</span><span className="demo-version">{data?`Publikacja ${data.data_version}`:'Wczytywanie danych'}</span></div>
        {offline&&<Notice tone="warning"><WifiOff size={15}/> Brak połączenia. Ostatni zapis: {dateTime(data?.cached_at||cacheGet<Bootstrap>(`mbod-public-view-v1-${layer.current}`)?.cached_at)}. Ten widok nie potwierdza bieżącego dojścia. Szkice pozostają niewysłane.</Notice>}
        {updated&&<Notice>Opublikowano nową wersję danych. Wyniki tras wymagają ponownego sprawdzenia. <button className="text-button" onClick={()=>{setUpdated(false);void evaluate();}}>Przelicz porównanie</button></Notice>}
        {error&&<Notice tone="error">{error} <button className="text-button" onClick={()=>void refresh()}>Spróbuj ponownie</button></Notice>}
        {loading&&!data?<Loading/>:data?<>
          {view==='resident'?<><Resident data={data} onReport={report}/><PrivateReports/></>:view==='comparison'?<><Comparison data={data} evaluation={evaluation} busy={evaluating} onEvaluate={request=>void evaluate(request)} onRefresh={refresh} onLogin={()=>setLoginOpen(true)}/><Resilience data={data}/></>:view==='evidence'?<EvidenceView data={data} onRefresh={refresh} onLogin={()=>setLoginOpen(true)}/>:view==='field'?<FieldTasks data={data} onRefresh={refresh} onLogin={()=>setLoginOpen(true)}/>:view==='sources'?<SourcesView data={data} onRefresh={refresh} onLogin={()=>setLoginOpen(true)}/>:view==='diagnostics'?<Diagnostics data={data} onLogin={()=>setLoginOpen(true)}/>:<Overview data={data} evaluation={evaluation} busy={evaluating} onEvaluate={()=>void evaluate()} onCompare={()=>navigate('comparison')} onResident={()=>navigate('resident')} onAsset={report}/>}
          <footer className="page-footer"><span>Miasto bez odcięć · DEFOZO SOFTWARE HOUSE</span><button onClick={()=>report()}><Send size={14}/>Zgłoś rozbieżność</button></footer>
        </>:!loading&&<section className="card"><h1>{selectedLayer==='observed'?'Brak opublikowanego obszaru obserwacji':'Nie udało się wczytać obszaru'}</h1><p>{selectedLayer==='observed'?'Wybierz Demonstrację, aby sprawdzić konflikt robót i porównać harmonogramy.':'Sprawdź połączenie i spróbuj pobrać dane ponownie.'}</p><Button onClick={()=>void refresh()}><RefreshCw size={16}/>Ponów odczyt</Button></section>}
      </main>
    </div>
    {loginOpen&&<Login localDemo={!!data?.local_demo_auth} onClose={()=>setLoginOpen(false)} onSuccess={async()=>{setLoginOpen(false);await refresh();}}/>}
    {reportOpen&&data&&<ReportForm data={data} asset={asset} onClose={()=>setReportOpen(false)} onRefresh={refresh}/>}
  </div>;
}
function Login({localDemo,onClose,onSuccess}:{localDemo:boolean;onClose:()=>void;onSuccess:()=>Promise<void>}) {
  const [role,setRole]=useState('operator'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const login=async(demo:boolean)=>{setBusy(true);setError('');try{const result=await api(demo?'/auth/demo':'/auth/login',demo?{role}:{username,password});setCsrf(result.csrf_token||'');setPassword('');await onSuccess();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <Modal title="Stanowisko operatora" onClose={onClose}><p className="muted">Zaloguj się, aby oceniać dowody, prowadzić kontrole i zapisywać decyzje.</p>{error&&<Notice tone="error">{error}</Notice>}{localDemo&&<div className="demo-login"><Badge tone="purple">DEMO · wybierz rolę</Badge><Field label="Rola w demonstracji"><select value={role} onChange={e=>setRole(e.target.value)}><option value="operator">Operator i koordynator</option><option value="verifier">Weryfikator terenowy</option><option value="admin">Administrator danych</option></select></Field><Button onClick={()=>void login(true)} busy={busy} className="full">Wejdź do demonstracji<ArrowRight size={16}/></Button></div>}<form onSubmit={e=>{e.preventDefault();void login(false);}}><Field label="Nazwa użytkownika"><input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required/></Field><Field label="Hasło"><input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></Field><Button type="submit" busy={busy} kind="secondary" className="full"><LogIn size={16}/>Zaloguj hasłem</Button></form></Modal>;
}
