import {useEffect,useId,useMemo,useState} from 'react';
import CityMap,{type MapViewport} from './CityMap';
import {type RecordData,rows,label,dateTime,formatNumber} from './api';
import {Badge,CardTitle,Empty,Field,Status} from './ui';

export function relationAt(relation:RecordData|undefined,time:string):RecordData|undefined {
 const instant=new Date(time).valueOf();return rows(relation?.intervals).find(interval=>new Date(interval.start).valueOf()<=instant&&instant<new Date(interval.end).valueOf());
}
export function RelationSnapshot({graph,evaluation,time}:{graph:RecordData;evaluation?:RecordData;time:string}) {
 const relations=rows(evaluation?.relations);
 const name=(items:unknown,id:string)=>label(rows(items).find(item=>item.id===id)||{id});
 return <section className="card relation-snapshot" aria-label="Relacje w wybranej chwili"><CardTitle title={`Wyjścia o ${dateTime(time,false)}`} action={<Badge>{relations.length} relacje</Badge>}/><p className="small muted">Stan obejmuje całe okno podróży rozpoczynającej się o tej porze. Ograniczenia na mapie pokazują stan w wybranej chwili.</p>{relations.length?<div className="table-scroll"><table><thead><tr><th>Początek i cel</th><th>Profil</th><th>Stan dojścia</th><th>Długość potwierdzonej lub możliwej trasy</th></tr></thead><tbody>{relations.map(relation=>{const interval=relationAt(relation,time);return <tr key={relation.id}><th>{name(graph.origins,relation.origin)} → {name(graph.places,relation.destination_id)}</th><td>{name(graph.profiles,relation.profile_id)}</td><td>{interval?<Status value={interval.status}/>:<span>Poza horyzontem rozpoczęć</span>}</td><td>{interval&&['confirmed','possible'].includes(interval.status)&&interval.distance_m!=null?`${formatNumber(interval.distance_m,0)} m`:'Brak wyznaczonej trasy'}</td></tr>;})}</tbody></table></div>:<Empty title="Oblicz analizę relacji">Wynik pokaże, które początki, profile i cele wymagają uwagi w wybranej chwili.</Empty>}</section>;
}

export default function ComparisonMaps({graph,baseline,variant,horizon}:{graph:RecordData;baseline:RecordData;variant:RecordData;horizon:RecordData}) {
 const timeDescriptionId=useId();
 const [time,setTime]=useState(horizon.start),[relationId,setRelationId]=useState(''),[viewport,setViewport]=useState<MapViewport>();
 const start=new Date(horizon.start).valueOf(),end=new Date(horizon.end).valueOf();
 useEffect(()=>{setTime(horizon.start);},[horizon.start,horizon.end]);
 const baselineGraph=useMemo(()=>({...graph,restrictions:baseline.restrictions||graph.restrictions}),[graph,baseline.restrictions]);
 const variantGraph=useMemo(()=>({...graph,restrictions:variant.restrictions||graph.restrictions}),[graph,variant.restrictions]);
 const relations=rows(baseline.relations),selected=relations.find(relation=>relation.id===relationId)||relations[0];
 const baseRoute=relationAt(selected,time),candidateRoute=relationAt(rows(variant.relations).find(relation=>relation.id===selected?.id),time);
 const relationName=(relation:RecordData)=>`${label(rows(graph.origins).find(origin=>origin.id===relation.origin)||{id:relation.origin})} → ${label(rows(graph.places).find(place=>place.id===relation.destination_id)||{id:relation.destination_id})} · ${label(rows(graph.profiles).find(profile=>profile.id===relation.profile_id)||{id:relation.profile_id})}`;
 return <section className="card comparison-maps" aria-label="Zsynchronizowane mapy porównania"><CardTitle title="Ten sam widok, dwa harmonogramy" action={<Badge tone="purple">Wspólna skala i czas</Badge>}/><p className="small muted">Przesunięcie lub przybliżenie jednej mapy zmienia także drugą. Kolor trasy dotyczy wybranej relacji i całego okna podróży.</p><Field label="Relacja na obu mapach"><select value={selected?.id||''} onChange={event=>setRelationId(event.target.value)}>{relations.map(relation=><option key={relation.id} value={relation.id}>{relationName(relation)}</option>)}</select></Field>{Number.isFinite(start)&&end>start&&<label className="field"><span id={timeDescriptionId} className="field-label">Początek podróży na obu mapach · {dateTime(time)}</span><input aria-label="Czas porównania map" aria-valuetext={dateTime(time,false)} aria-describedby={timeDescriptionId} type="range" min={0} max={(end-start)/60000} step={5} value={(new Date(time).valueOf()-start)/60000} onChange={event=>setTime(new Date(start+Number(event.target.value)*60000).toISOString())}/></label>}<div className="comparison-grid"><div><h3>Plan bazowy</h3><p className="small">Cały horyzont: <strong>{formatNumber(baseline.available_relation_hours)} h dostępnych relacji</strong></p>{baseRoute?<Status value={baseRoute.status}/>:<Badge>Poza horyzontem rozpoczęć</Badge>}<CityMap graph={baselineGraph} route={baseRoute} selectedTime={time} viewport={viewport} onViewportChange={setViewport} compact/></div><div><h3>{variant.name||'Wybrany wariant'}</h3><p className="small">Cały horyzont: <strong>{formatNumber(variant.available_relation_hours)} h dostępnych relacji</strong></p>{candidateRoute?<Status value={candidateRoute.status}/>:<Badge>Poza horyzontem rozpoczęć</Badge>}<CityMap graph={variantGraph} route={candidateRoute} selectedTime={time} viewport={viewport} onViewportChange={setViewport} compact/></div></div><p className="small muted">Pełne wyniki wszystkich relacji są dostępne w tabelach poniżej, bez korzystania z mapy.</p></section>;
}
