import {useState} from 'react';
import {CheckCircle2,FileText,History,RefreshCw} from 'lucide-react';
import {api,type Bootstrap,type RecordData,rows,label,dateTime} from './api';
import {Badge,Button,CardTitle,Field,Notice,Status} from './ui';

export function SourceDetail({source,onCandidate}:{source:RecordData;onCandidate:(candidate:RecordData)=>void}) {
  const [detail,setDetail]=useState<RecordData|null>(null),[candidate,setCandidate]=useState<RecordData|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[useAi,setUseAi]=useState(false);
  const run=async(extract:boolean)=>{setBusy(true);setError('');try{if(extract)setCandidate(await api(`/sources/${source.id}/extract`,{use_ai:useAi}));else setDetail(await api(`/sources/${source.id}`));}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <div><div className="row-actions"><Button kind="secondary" busy={busy} onClick={()=>void run(false)}><FileText size={14}/>Odczytaj materiał i historię</Button><Button kind="secondary" busy={busy} onClick={()=>void run(true)}>Przygotuj kandydaturę</Button></div><label className="check-label"><input type="checkbox" checked={useAi} onChange={e=>setUseAi(e.target.checked)}/>Użyj skonfigurowanej ekstrakcji AI (opcjonalnie)</label>{error&&<Notice tone="error">{error}</Notice>}{detail&&<><p className="source-text">{detail.raw_text||'Brak tekstu w tym materiale.'}</p><details className="evidence-details"><summary>Historia zachowanych wersji</summary>{rows(detail.snapshots).map(snapshot=><div className="evidence-row" key={snapshot.id}><span>{dateTime(snapshot.fetched_at||snapshot.created_at)}</span><code className="break-word">{snapshot.sha256}</code></div>)}</details></>}{candidate&&<><Notice tone="warning">Kandydatura wymaga kontroli. Brakujące wartości pozostają puste. Cytowany fragment musi uzasadniać wpisane pole.</Notice><pre className="data-detail">{JSON.stringify(candidate,null,2)}</pre><Button kind="secondary" onClick={()=>onCandidate({...candidate,source_id:source.id})}>Przenieś do formularza przeglądu</Button></>}</div>;
}

export function OpeningControls({data,onRefresh}:{data:Bootstrap;onRefresh:()=>Promise<void>}) {
  const [selected,setSelected]=useState(''),[evidenceId,setEvidenceId]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const restrictions=rows(data.restrictions).filter(r=>!r.verified_open_at&&r.kind==='closure');
  const restriction=restrictions.find(r=>r.id===selected)||restrictions[0];
  const evidence=rows(data.staff_evidence).filter(e=>e.asset_id===restriction?.asset_id&&e.feature==='open'&&e.value===true&&e.status==='confirmed'&&!['fixture','controlled_fixture'].includes(e.method));
  const submit=async()=>{if(!restriction)return;setBusy(true);setError('');try{const item=evidence.find(e=>e.id===evidenceId);await api(`/restrictions/${restriction.id}/open`,{layer:data.layer,expected_version:restriction.version||1,evidence_id:evidenceId,observed_at:item?.observed_at,reason});setMessage('Otwarcie opublikowano na podstawie wskazanej obserwacji. Trasy wymagają ponownego obliczenia.');setEvidenceId('');await onRefresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  if(!restrictions.length)return null;
  return <section className="card"><CardTitle title="Potwierdź otwarcie po zakończeniu robót" action={<CheckCircle2 size={20}/>}/><p className="muted">Termin w planie nie otwiera przejścia. Wskaż nowy, opublikowany dowód otwarcia dokładnie tego obiektu.</p><form onSubmit={e=>{e.preventDefault();void submit();}}><div className="form-grid"><Field label="Zamknięcie do rozstrzygnięcia"><select value={restriction?.id||''} onChange={e=>{setSelected(e.target.value);setEvidenceId('');}}>{restrictions.map(r=><option key={r.id} value={r.id}>{label(rows(data.graph.assets).find(a=>a.id===r.asset_id))} · od {dateTime(r.start)}</option>)}</select></Field><Field label="Opublikowana obserwacja otwarcia"><select required value={evidenceId} onChange={e=>setEvidenceId(e.target.value)}><option value="">Wybierz nowy dowód otwarcia</option>{evidence.map(e=><option key={e.id} value={e.id}>{dateTime(e.observed_at)} · {e.method} · {e.id}</option>)}</select></Field></div><Field label="Uzasadnienie publikacji otwarcia"><textarea required minLength={3} value={reason} onChange={e=>setReason(e.target.value)} rows={2}/></Field>{error&&<Notice tone="error">{error}</Notice>}{message&&<Notice tone="success">{message}</Notice>}<Button busy={busy} type="submit" disabled={!evidenceId}>Opublikuj potwierdzone otwarcie</Button></form></section>;
}

export function EvidenceHistory({evidenceId}:{evidenceId:string}) {
 const [history,setHistory]=useState<RecordData[]|null>(null),[error,setError]=useState('');
 return <><Button kind="ghost" onClick={()=>{void api(`/evidence/${evidenceId}/history`).then(v=>setHistory(rows(v))).catch(e=>setError(e.message));}}><History size={13}/>Historia cechy</Button>{error&&<Notice tone="error">{error}</Notice>}{history&&<details open className="evidence-details"><summary>Wersje obserwacji</summary>{history.map(e=><p key={e.id} className="small">{dateTime(e.observed_at)} · {String(e.value)} {e.unit} · <Status value={e.status}/><br/>{e.review_reason||e.method}</p>)}</details>}</>;
}

export function GraphStaging({data,onRefresh}:{data:Bootstrap;onRefresh:()=>Promise<void>}) {
 const [graphs,setGraphs]=useState<RecordData[]>([]),[error,setError]=useState(''),[selected,setSelected]=useState<RecordData|null>(null),[bindings,setBindings]=useState('{}'),[graphText,setGraphText]=useState('{}'),[busy,setBusy]=useState(false);
 const load=async()=>{setBusy(true);try{setGraphs(rows(await api(`/graphs?layer=${data.layer}`)));setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const action=async(publish:boolean)=>{if(!selected)return;setBusy(true);setError('');try{const result=await api(`/graphs/${selected.id}/${publish?'publish':'validate'}`,{expected_version:selected.version,...(!publish?{bindings:JSON.parse(bindings)}:{})});setSelected({...selected,...result});await load();if(publish)await onRefresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const save=async()=>{if(!selected)return;setBusy(true);setError('');try{setSelected(await api(`/graphs/${selected.id}/edit`,{expected_version:selected.version,graph:JSON.parse(graphText),bindings:JSON.parse(bindings)}));await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <section className="card"><CardTitle title="Wersje grafu i powiązania obiektów" action={<Button kind="secondary" onClick={()=>void load()} busy={busy}><RefreshCw size={15}/>Wczytaj wersje</Button>}/><p className="muted">Niejasne przypisanie ograniczenia zatrzymuje publikację. Administrator publikuje graf i powiązania w jednej operacji.</p>{error&&<Notice tone="error">{error}</Notice>}{graphs.map(g=><button key={g.id} className="scenario-row" onClick={()=>{setSelected(g);setBindings(JSON.stringify(g.bindings||{},null,2));setGraphText(JSON.stringify(g.graph,null,2));}}><div><strong>{g.graph?.name||g.id}</strong><span>{dateTime(g.created_at)}</span></div><Status value={g.status}/><Badge>{g.graph?.edges?.length||0} odcinków</Badge></button>)}{selected&&<>{selected.status!=='published'&&<details className="evidence-details"><summary>Uzupełnij topologię, wejścia, profile i punkty oceny</summary><Notice>Import nie potwierdza cech dostępności. Wymagane są profile (profiles), punkty początkowe w istniejących węzłach (origins), cele (places), wejścia (entrances) i wspólny horyzont (horizon). Nie dopisuj dowodów bez obserwacji.</Notice><Field label="Edytowalny graf w obszarze roboczym"><textarea className="code-input" rows={15} value={graphText} onChange={e=>setGraphText(e.target.value)}/></Field><div className="row-actions"><Button kind="secondary" onClick={()=>{try{const graph=JSON.parse(graphText);setGraphText(JSON.stringify({...graph,profiles:graph.profiles?.length?graph.profiles:data.graph.profiles,origins:graph.origins?.length?graph.origins:(graph.nodes||[]).slice(0,1).map((n:RecordData)=>({...n,name:n.name||'Punkt oceny do zatwierdzenia'})),horizon:graph.horizon||data.graph.horizon,clock:graph.clock||data.graph.clock},null,2));}catch(e){setError((e as Error).message);}}}>Wstaw edytowalne ustawienia początkowe</Button><Button busy={busy} onClick={()=>void save()}>Zapisz uzupełnienie grafu</Button></div></details>}<Field label="Powiązania stabilnych obiektów z odcinkami nowego grafu" hint={'Format JSON: {"asset_id": ["edge_id"]}. Lista i geometria grafu są poniżej.'}><textarea rows={4} className="code-input" value={bindings} onChange={e=>setBindings(e.target.value)}/></Field><div className="row-actions"><Button kind="secondary" busy={busy} onClick={()=>void action(false)}>Sprawdź graf i przypisania</Button>{data.user?.role==='admin'&&<Button busy={busy} disabled={!selected.quality?.valid||selected.status==='published'} onClick={()=>void action(true)}>Opublikuj nową wersję</Button>}</div><pre className="data-detail">{JSON.stringify(selected.quality||selected.graph,null,2)}</pre></>}</section>;
}
